const LANGUAGES = [
  { id: 1, name: 'Arabic', isoCode: 'ar', originalName: 'العربية' },
  { id: 2, name: 'Belarusian', isoCode: 'be', originalName: 'Беларуская' },
  { id: 3, name: 'Bengali', isoCode: 'bn', originalName: 'বাংলা' },
  { id: 4, name: 'Bulgarian', isoCode: 'bg', originalName: 'Български' },
  { id: 5, name: 'Chinese', isoCode: 'zh', originalName: '中文' },
  { id: 6, name: 'Czech', isoCode: 'cs', originalName: 'Čeština' },
  { id: 7, name: 'Danish', isoCode: 'da', originalName: 'Dansk' },
  { id: 8, name: 'Dutch', isoCode: 'nl', originalName: 'Nederlands' },
  { id: 9, name: 'English', isoCode: 'en', originalName: 'English' },
  { id: 10, name: 'Estonian', isoCode: 'et', originalName: 'Eesti' },
  { id: 11, name: 'Finnish', isoCode: 'fi', originalName: 'Suomi' },
  { id: 12, name: 'French', isoCode: 'fr', originalName: 'Français' },
  { id: 13, name: 'German', isoCode: 'de', originalName: 'Deutsch' },
  { id: 14, name: 'Greek', isoCode: 'el', originalName: 'Ελληνικά' },
  { id: 15, name: 'Hebrew', isoCode: 'he', originalName: 'עברית' },
  { id: 16, name: 'Hindi', isoCode: 'hi', originalName: 'हिन्दी' },
  { id: 17, name: 'Hungarian', isoCode: 'hu', originalName: 'Magyar' },
  { id: 18, name: 'Indonesian', isoCode: 'id', originalName: 'Bahasa Indonesia' },
  { id: 19, name: 'Italian', isoCode: 'it', originalName: 'Italiano' },
  { id: 20, name: 'Japanese', isoCode: 'ja', originalName: '日本語' },
  { id: 21, name: 'Korean', isoCode: 'ko', originalName: '한국어' },
  { id: 22, name: 'Latvian', isoCode: 'lv', originalName: 'Latviešu' },
  { id: 23, name: 'Lithuanian', isoCode: 'lt', originalName: 'Lietuvių' },
  { id: 24, name: 'Norwegian', isoCode: 'nb', originalName: 'Norsk' },
  { id: 25, name: 'Persian', isoCode: 'fa', originalName: 'فارسی' },
  { id: 26, name: 'Polish', isoCode: 'pl', originalName: 'Polski' },
  { id: 27, name: 'Portuguese', isoCode: 'pt', originalName: 'Português' },
  { id: 28, name: 'Romanian', isoCode: 'ro', originalName: 'Română' },
  { id: 29, name: 'Russian', isoCode: 'ru', originalName: 'Русский' },
  { id: 30, name: 'Slovak', isoCode: 'sk', originalName: 'Slovenčina' },
  { id: 31, name: 'Slovenian', isoCode: 'sl', originalName: 'Slovenščina' },
  { id: 32, name: 'Spanish', isoCode: 'es', originalName: 'Español' },
  { id: 33, name: 'Swahili', isoCode: 'sw', originalName: 'Kiswahili' },
  { id: 34, name: 'Swedish', isoCode: 'sv', originalName: 'Svenska' },
  { id: 35, name: 'Thai', isoCode: 'th', originalName: 'ไทย' },
  { id: 36, name: 'Turkish', isoCode: 'tr', originalName: 'Türkçe' },
  { id: 37, name: 'Ukrainian', isoCode: 'uk', originalName: 'Українська' },
  { id: 38, name: 'Urdu', isoCode: 'ur', originalName: 'اردو' },
  { id: 39, name: 'Vietnamese', isoCode: 'vi', originalName: 'Tiếng Việt' },
];

export { LANGUAGES };

export function loadLocales() {
  return LANGUAGES.map((lang) => lang.isoCode);
}
